/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ultrafast_secp256k1_Secp256k1 */

#ifndef _Included_com_ultrafast_secp256k1_Secp256k1
#define _Included_com_ultrafast_secp256k1_Secp256k1
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ultrafast_secp256k1_Secp256k1_NETWORK_MAINNET
#define com_ultrafast_secp256k1_Secp256k1_NETWORK_MAINNET 0L
#undef com_ultrafast_secp256k1_Secp256k1_NETWORK_TESTNET
#define com_ultrafast_secp256k1_Secp256k1_NETWORK_TESTNET 1L
/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecPubkeyCreate
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecPubkeyCreate
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecPubkeyCreateUncompressed
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecPubkeyCreateUncompressed
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecPubkeyParse
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecPubkeyParse
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecSeckeyVerify
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecSeckeyVerify
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecPrivkeyNegate
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecPrivkeyNegate
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecPrivkeyTweakAdd
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecPrivkeyTweakAdd
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecPrivkeyTweakMul
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecPrivkeyTweakMul
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecdsaSign
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecdsaSign
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecdsaVerify
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecdsaVerify
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecdsaSerializeDer
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecdsaSerializeDer
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecdsaSignRecoverable
 * Signature: ([B[B)Lcom/ultrafast/secp256k1/Secp256k1/RecoverableSignature;
 */
JNIEXPORT jobject JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecdsaSignRecoverable
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecdsaRecover
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecdsaRecover
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    schnorrSign
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_schnorrSign
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    schnorrVerify
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ultrafast_secp256k1_Secp256k1_schnorrVerify
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    schnorrPubkey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_schnorrPubkey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecdh
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecdh
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecdhXonly
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecdhXonly
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    ecdhRaw
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_ecdhRaw
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    sha256
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_sha256
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    hash160
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_hash160
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    taggedHash
 * Signature: (Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_taggedHash
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    addressP2pkh
 * Signature: ([BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ultrafast_secp256k1_Secp256k1_addressP2pkh
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    addressP2wpkh
 * Signature: ([BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ultrafast_secp256k1_Secp256k1_addressP2wpkh
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    addressP2tr
 * Signature: ([BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ultrafast_secp256k1_Secp256k1_addressP2tr
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    wifEncode
 * Signature: ([BZI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ultrafast_secp256k1_Secp256k1_wifEncode
  (JNIEnv *, jclass, jbyteArray, jboolean, jint);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    wifDecode
 * Signature: (Ljava/lang/String;)Lcom/ultrafast/secp256k1/Secp256k1/WifDecodeResult;
 */
JNIEXPORT jobject JNICALL Java_com_ultrafast_secp256k1_Secp256k1_wifDecode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    bip32MasterKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_bip32MasterKey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    bip32DeriveChild
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_bip32DeriveChild
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    bip32DerivePath
 * Signature: ([BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_bip32DerivePath
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    bip32GetPrivkey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_bip32GetPrivkey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    bip32GetPubkey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_bip32GetPubkey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    taprootOutputKey
 * Signature: ([B[B)Lcom/ultrafast/secp256k1/Secp256k1/TaprootOutputKeyResult;
 */
JNIEXPORT jobject JNICALL Java_com_ultrafast_secp256k1_Secp256k1_taprootOutputKey
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    taprootTweakPrivkey
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ultrafast_secp256k1_Secp256k1_taprootTweakPrivkey
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    taprootVerifyCommitment
 * Signature: ([BI[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ultrafast_secp256k1_Secp256k1_taprootVerifyCommitment
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ultrafast_secp256k1_Secp256k1_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_ultrafast_secp256k1_Secp256k1
 * Method:    nativeVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ultrafast_secp256k1_Secp256k1_nativeVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
