#!/usr/bin/env python3
"""
render_audit_dashboard.py — emit `docs/AUDIT_DASHBOARD.md`.

Single-page Markdown summary of the assurance posture pulled from the
JSON evidence already produced by other tools. Designed to be regenerated
by the nightly `caas-evidence-refresh.yml` workflow (CAAS hardening H-1)
and committed alongside the refreshed evidence.

Implements CAAS hardening item H-9 (see `docs/CAAS_HARDENING_TODO.md`).

Usage:
    python3 scripts/render_audit_dashboard.py [-o docs/AUDIT_DASHBOARD.md]
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
SUITE_ROOT = REPO_ROOT.parent.parent  # …/Secp256K1fast


def _load_json(path: Path) -> dict[str, Any] | None:
    try:
        return json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return None


def _row(label: str, value: Any) -> str:
    return f'| {label} | {value} |'


def _section(title: str) -> str:
    return f'\n## {title}\n'


def _format_autonomy(kpi: dict[str, Any] | None) -> str:
    if not kpi:
        return '_No SECURITY_AUTONOMY_KPI.json available._'
    score = kpi.get('total_score', kpi.get('score', '?'))
    out = [f'**Score:** {score} / 100', '']
    out.append('| Component | Score |')
    out.append('|-----------|-------|')
    for k, v in (kpi.get('breakdown') or kpi.get('components') or {}).items():
        out.append(_row(k, v))
    return '\n'.join(out)


def _format_assurance(rep: dict[str, Any] | None) -> str:
    if not rep:
        return '_No assurance_report.json available._'
    out = ['| Field | Value |', '|-------|-------|']
    for k in ('generated_at', 'overall_pass', 'release_ready',
              'failed_modules', 'advisory_failed', 'advisory_skipped'):
        if k in rep:
            v = rep[k]
            if isinstance(v, list):
                v = ', '.join(map(str, v)) or '(none)'
            out.append(_row(k, v))
    return '\n'.join(out)


def _format_residual(reg_path: Path) -> str:
    try:
        text = reg_path.read_text()
    except OSError:
        return '_No RESIDUAL_RISK_REGISTER.md available._'
    lines = text.splitlines()
    table = [ln for ln in lines if ln.startswith('| RR-')]
    if not table:
        return '_Register table empty._'
    return '\n'.join(['| ID | Status (one-line) |', '|----|-------------------|']
                     + [f"| {ln.split('|')[1].strip()} | "
                        f"{ln.split('|')[3].strip()} |"
                        for ln in table])


def _format_caas_hardening(todo_path: Path) -> str:
    try:
        text = todo_path.read_text()
    except OSError:
        return '_No CAAS_HARDENING_TODO.md available._'
    done = text.count('✓ Done')
    items = sum(1 for ln in text.splitlines() if ln.startswith('### H-'))
    pct = (100 * done // items) if items else 0
    return (f'**Hardening progress:** {done} / {items} items closed ({pct} %).\n'
            f'See [`docs/CAAS_HARDENING_TODO.md`](CAAS_HARDENING_TODO.md).')


def render() -> str:
    out: list[str] = []
    out.append('# Audit Dashboard')
    out.append('')
    out.append(f'_Generated {datetime.now(timezone.utc).isoformat()}._')
    out.append('')
    out.append('> Auto-generated by `scripts/render_audit_dashboard.py`. ')
    out.append('> Refreshed nightly by the `caas-evidence-refresh` workflow.')
    out.append('')

    out.append(_section('Security Autonomy KPI'))
    out.append(_format_autonomy(_load_json(REPO_ROOT / 'docs' / 'SECURITY_AUTONOMY_KPI.json')))

    out.append(_section('Assurance Report'))
    rep = _load_json(SUITE_ROOT / 'assurance_report.json') \
        or _load_json(REPO_ROOT / 'assurance_report.json')
    out.append(_format_assurance(rep))

    out.append(_section('Residual Risk Register (snapshot)'))
    out.append(_format_residual(REPO_ROOT / 'docs' / 'RESIDUAL_RISK_REGISTER.md'))

    out.append(_section('CAAS Hardening Progress'))
    out.append(_format_caas_hardening(REPO_ROOT / 'docs' / 'CAAS_HARDENING_TODO.md'))

    out.append('')
    return '\n'.join(out) + '\n'


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('-o', '--output',
                   default=str(REPO_ROOT / 'docs' / 'AUDIT_DASHBOARD.md'),
                   help='output Markdown path')
    args = p.parse_args()
    Path(args.output).write_text(render())
    print(f'render_audit_dashboard: wrote {args.output}', file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
