#ifndef SECP256K1_VERSION_HPP_IN
#define SECP256K1_VERSION_HPP_IN
#pragma once

// Auto-generated by CMake — DO NOT EDIT
// Source: cmake/version.hpp.in

#define SECP256K1_VERSION_MAJOR 3
#define SECP256K1_VERSION_MINOR 66
#define SECP256K1_VERSION_PATCH 0
#define SECP256K1_VERSION_STRING "3.66.0"

namespace secp256k1 {

struct Version {
    static constexpr int major = 3;
    static constexpr int minor = 66;
    static constexpr int patch = 0;
    static constexpr const char* string = "3.66.0";
};

} // namespace secp256k1

#endif // SECP256K1_VERSION_HPP_IN
