UltrafastSecp256k1: secp256k1::SHA256 Class Reference
secp256k1::SHA256 Class Reference
#include <sha256.hpp>
Public Types
using digest_type = std::array< std::uint8_t, 32 >
Public Member Functions
SHA256 () noexcept
void reset () noexcept
void update (const void *data, std::size_t len) noexcept
digest_type finalize () noexcept
Static Public Member Functions
static digest_type hash (const void *data, std::size_t len) noexcept
static digest_type hash256 (const void *data, std::size_t len) noexcept
Detailed Description
Definition at line 25 of file sha256.hpp.
Member Typedef Documentation
digest_type
using secp256k1::SHA256::digest_type = std::array<std::uint8_t, 32>
Definition at line 27 of file sha256.hpp.
Constructor & Destructor Documentation
SHA256()
secp256k1::SHA256::SHA256 () inline noexcept
Definition at line 29 of file sha256.hpp.
References reset().
Member Function Documentation
finalize()
digest_type secp256k1::SHA256::finalize () inline noexcept
Definition at line 70 of file sha256.hpp.
References update().
Referenced by hash(), and ufsecp_sha256().
hash()
static digest_type secp256k1::SHA256::hash (const void * data, std::size_t len) inline static noexcept
Definition at line 100 of file sha256.hpp.
References finalize(), and update().
Referenced by hash256().
hash256()
static digest_type secp256k1::SHA256::hash256 (const void * data, std::size_t len) inline static noexcept
Definition at line 107 of file sha256.hpp.
References hash().
reset()
void secp256k1::SHA256::reset () inline noexcept
Definition at line 31 of file sha256.hpp.
Referenced by SHA256().
update()
void secp256k1::SHA256::update (const void * data, std::size_t len) inline noexcept
Definition at line 40 of file sha256.hpp.
References secp256k1::detail::sha256_compress_dispatch().
Referenced by finalize(), hash(), and ufsecp_sha256().
The documentation for this class was generated from the following file:
cpu/include/secp256k1/sha256.hpp