UltrafastSecp256k1: secp256k1::PrivateKey Class Reference
secp256k1::PrivateKey Class Reference
#include <private_key.hpp>
Public Member Functions
PrivateKey () noexcept=default
const fast::Scalar & scalar () const noexcept
std::array< std::uint8_t, 32 > to_bytes () const
bool is_valid () const noexcept
~PrivateKey ()
PrivateKey (const PrivateKey &other) noexcept
PrivateKey & operator= (const PrivateKey &other) noexcept
PrivateKey (PrivateKey &&other) noexcept
PrivateKey & operator= (PrivateKey &&other) noexcept
Static Public Member Functions
static bool from_bytes (const std::uint8_t *bytes32, PrivateKey &out) noexcept
static bool from_bytes (const std::array< std::uint8_t, 32 > &bytes, PrivateKey &out) noexcept
static PrivateKey wrap (const fast::Scalar &s) noexcept
Detailed Description
Definition at line 31 of file private_key.hpp.
Constructor & Destructor Documentation
PrivateKey() [1/3]
secp256k1::PrivateKey::PrivateKey () default noexcept
~PrivateKey()
secp256k1::PrivateKey::~PrivateKey () inline
Definition at line 78 of file private_key.hpp.
PrivateKey() [2/3]
secp256k1::PrivateKey::PrivateKey (const PrivateKey & other) inline noexcept
Definition at line 81 of file private_key.hpp.
PrivateKey() [3/3]
secp256k1::PrivateKey::PrivateKey (PrivateKey && other) inline noexcept
Definition at line 91 of file private_key.hpp.
Member Function Documentation
from_bytes() [1/2]
static bool secp256k1::PrivateKey::from_bytes (const std::array< std::uint8_t, 32 > & bytes, PrivateKey & out) inline static noexcept
Definition at line 44 of file private_key.hpp.
References secp256k1::fast::Scalar::parse_bytes_strict_nonzero().
from_bytes() [2/2]
static bool secp256k1::PrivateKey::from_bytes (const std::uint8_t * bytes32, PrivateKey & out) inline static noexcept
Definition at line 40 of file private_key.hpp.
References secp256k1::fast::Scalar::parse_bytes_strict_nonzero().
is_valid()
bool secp256k1::PrivateKey::is_valid () const inline noexcept
Definition at line 70 of file private_key.hpp.
References secp256k1::fast::Scalar::is_zero().
operator=() [1/2]
PrivateKey & secp256k1::PrivateKey::operator= (const PrivateKey & other) inline noexcept
Definition at line 82 of file private_key.hpp.
operator=() [2/2]
PrivateKey & secp256k1::PrivateKey::operator= (PrivateKey && other) inline noexcept
Definition at line 94 of file private_key.hpp.
scalar()
const fast::Scalar & secp256k1::PrivateKey::scalar () const inline noexcept
Definition at line 62 of file private_key.hpp.
Referenced by secp256k1::ct::ecdsa_sign(), secp256k1::ct::ecdsa_sign_hedged(), secp256k1::ct::ecdsa_sign_hedged_verified(), secp256k1::ct::ecdsa_sign_verified(), secp256k1::ct::schnorr_keypair_create(), and secp256k1::ct::schnorr_pubkey().
to_bytes()
std::array< std::uint8_t, 32 > secp256k1::PrivateKey::to_bytes () const inline
Definition at line 65 of file private_key.hpp.
References secp256k1::fast::Scalar::to_bytes().
wrap()
static PrivateKey secp256k1::PrivateKey::wrap (const fast::Scalar & s) inline static noexcept
Definition at line 51 of file private_key.hpp.
The documentation for this class was generated from the following file:
cpu/include/secp256k1/private_key.hpp