UltrafastSecp256k1: secp256k1::fast::Scalar Class Reference
secp256k1::fast::Scalar Class Reference
#include <scalar.hpp>
Public Types
using limbs_type = std::array< std::uint64_t, 4 >
Public Member Functions
Scalar ()
std::array< std::uint8_t, 32 > to_bytes () const
std::string to_hex () const
const limbs_type & limbs () const noexcept
Scalar operator+ (const Scalar &rhs) const
Scalar operator- (const Scalar &rhs) const
Scalar operator* (const Scalar &rhs) const
Scalar & operator+= (const Scalar &rhs)
Scalar & operator-= (const Scalar &rhs)
Scalar & operator*= (const Scalar &rhs)
bool is_zero () const noexcept
bool operator== (const Scalar &rhs) const noexcept
bool operator!= (const Scalar &rhs) const noexcept
Scalar inverse () const
Scalar negate () const
bool is_even () const noexcept
const ::secp256k1::ScalarData & data () const noexcept
::secp256k1::ScalarData & data () noexcept
std::uint8_t bit (std::size_t index) const
std::vector< int8_t > to_naf () const
std::vector< int8_t > to_wnaf (unsigned width) const
Static Public Member Functions
static Scalar zero ()
static Scalar one ()
static Scalar from_uint64 (std::uint64_t value)
static Scalar from_limbs (const limbs_type &limbs)
static Scalar from_bytes (const std::array< std::uint8_t, 32 > &bytes)
static Scalar from_hex (const std::string &hex)
static Scalar from_data (const ::secp256k1::ScalarData &d)
Detailed Description
Definition at line 13 of file scalar.hpp.
Member Typedef Documentation
limbs_type
using secp256k1::fast::Scalar::limbs_type = std::array<std::uint64_t, 4>
Definition at line 15 of file scalar.hpp.
Constructor & Destructor Documentation
Scalar()
secp256k1::fast::Scalar::Scalar ()
Member Function Documentation
bit()
std::uint8_t secp256k1::fast::Scalar::bit (std::size_t index) const
data() [1/2]
const ::secp256k1::ScalarData & secp256k1::fast::Scalar::data () const inline noexcept
Definition at line 55 of file scalar.hpp.
data() [2/2]
::secp256k1::ScalarData & secp256k1::fast::Scalar::data () inline noexcept
Definition at line 58 of file scalar.hpp.
from_bytes()
static Scalar secp256k1::fast::Scalar::from_bytes (const std::array< std::uint8_t, 32 > & bytes) static
Referenced by scalar_from_bytes().
from_data()
static Scalar secp256k1::fast::Scalar::from_data (const ::secp256k1::ScalarData & d) inline static
Definition at line 61 of file scalar.hpp.
References from_limbs().
from_hex()
static Scalar secp256k1::fast::Scalar::from_hex (const std::string & hex) static
from_limbs()
static Scalar secp256k1::fast::Scalar::from_limbs (const limbs_type & limbs) static
Referenced by from_data().
from_uint64()
static Scalar secp256k1::fast::Scalar::from_uint64 (std::uint64_t value) static
inverse()
Scalar secp256k1::fast::Scalar::inverse () const
is_even()
bool secp256k1::fast::Scalar::is_even () const noexcept
is_zero()
bool secp256k1::fast::Scalar::is_zero () const noexcept
limbs()
const limbs_type & secp256k1::fast::Scalar::limbs () const inline noexcept
Definition at line 30 of file scalar.hpp.
negate()
Scalar secp256k1::fast::Scalar::negate () const
one()
static Scalar secp256k1::fast::Scalar::one () static
operator!=()
bool secp256k1::fast::Scalar::operator!= (const Scalar & rhs) const inline noexcept
Definition at line 42 of file scalar.hpp.
operator*()
Scalar secp256k1::fast::Scalar::operator* (const Scalar & rhs) const
operator*=()
Scalar & secp256k1::fast::Scalar::operator*= (const Scalar & rhs)
operator+()
Scalar secp256k1::fast::Scalar::operator+ (const Scalar & rhs) const
operator+=()
Scalar & secp256k1::fast::Scalar::operator+= (const Scalar & rhs)
operator-()
Scalar secp256k1::fast::Scalar::operator- (const Scalar & rhs) const
operator-=()
Scalar & secp256k1::fast::Scalar::operator-= (const Scalar & rhs)
operator==()
bool secp256k1::fast::Scalar::operator== (const Scalar & rhs) const noexcept
to_bytes()
std::array< std::uint8_t, 32 > secp256k1::fast::Scalar::to_bytes () const
Referenced by scalar_to_bytes().
to_hex()
std::string secp256k1::fast::Scalar::to_hex () const
to_naf()
std::vector< int8_t > secp256k1::fast::Scalar::to_naf () const
to_wnaf()
std::vector< int8_t > secp256k1::fast::Scalar::to_wnaf (unsigned width) const
zero()
static Scalar secp256k1::fast::Scalar::zero () static
The documentation for this class was generated from the following file:
cpu/include/secp256k1/scalar.hpp