UltrafastSecp256k1: secp256k1::fast::FieldElement Class Reference
secp256k1::fast::FieldElement Class Reference
#include <field.hpp>
Public Types
using limbs_type = std::array< std::uint64_t, 4 >
Public Member Functions
FieldElement ()
std::array< std::uint8_t, 32 > to_bytes () const
void to_bytes_into (std::uint8_t *out) const noexcept
std::string to_hex () const
const limbs_type & limbs () const noexcept
FieldElement operator+ (const FieldElement &rhs) const
FieldElement operator- (const FieldElement &rhs) const
FieldElement operator* (const FieldElement &rhs) const
FieldElement square () const
FieldElement inverse () const
FieldElement sqrt () const
FieldElement & operator+= (const FieldElement &rhs)
FieldElement & operator-= (const FieldElement &rhs)
FieldElement & operator*= (const FieldElement &rhs)
FieldElement negate (unsigned=1) const
void negate_assign (unsigned=1)
void square_inplace ()
void inverse_inplace ()
bool operator== (const FieldElement &rhs) const noexcept
bool operator!= (const FieldElement &rhs) const noexcept
const ::secp256k1::FieldElementData & data () const noexcept
::secp256k1::FieldElementData & data () noexcept
Static Public Member Functions
static FieldElement zero ()
static FieldElement one ()
static FieldElement from_uint64 (std::uint64_t value)
static FieldElement from_limbs (const limbs_type &limbs)
static FieldElement from_bytes (const std::array< std::uint8_t, 32 > &bytes)
static FieldElement from_mont (const FieldElement &a)
static FieldElement from_hex (const std::string &hex)
static FieldElement from_limbs_raw (const limbs_type &limbs) noexcept
static FieldElement from_data (const ::secp256k1::FieldElementData &d)
Detailed Description
Definition at line 42 of file field.hpp.
Member Typedef Documentation
limbs_type
using secp256k1::fast::FieldElement::limbs_type = std::array<std::uint64_t, 4>
Definition at line 44 of file field.hpp.
Constructor & Destructor Documentation
FieldElement()
secp256k1::fast::FieldElement::FieldElement ()
Member Function Documentation
data() [1/2]
const ::secp256k1::FieldElementData & secp256k1::fast::FieldElement::data () const inline noexcept
Definition at line 108 of file field.hpp.
data() [2/2]
::secp256k1::FieldElementData & secp256k1::fast::FieldElement::data () inline noexcept
Definition at line 111 of file field.hpp.
from_bytes()
static FieldElement secp256k1::fast::FieldElement::from_bytes (const std::array< std::uint8_t, 32 > & bytes) static
Referenced by point_from_compressed(), and ufsecp_pubkey_parse().
from_data()
static FieldElement secp256k1::fast::FieldElement::from_data (const ::secp256k1::FieldElementData & d) inline static
Definition at line 114 of file field.hpp.
References from_limbs().
from_hex()
static FieldElement secp256k1::fast::FieldElement::from_hex (const std::string & hex) static
from_limbs()
static FieldElement secp256k1::fast::FieldElement::from_limbs (const limbs_type & limbs) static
Referenced by secp256k1::fast::field_select(), and from_data().
from_limbs_raw()
static FieldElement secp256k1::fast::FieldElement::from_limbs_raw (const limbs_type & limbs) inline static noexcept
Definition at line 68 of file field.hpp.
References limbs().
from_mont()
static FieldElement secp256k1::fast::FieldElement::from_mont (const FieldElement & a) static
from_uint64()
static FieldElement secp256k1::fast::FieldElement::from_uint64 (std::uint64_t value) static
Referenced by point_from_compressed().
inverse()
FieldElement secp256k1::fast::FieldElement::inverse () const
Referenced by secp256k1::fast::fe_h_based_inversion(), and secp256k1::fast::fe_h_based_inversion_batched().
inverse_inplace()
void secp256k1::fast::FieldElement::inverse_inplace ()
limbs()
const limbs_type & secp256k1::fast::FieldElement::limbs () const inline noexcept
Definition at line 64 of file field.hpp.
Referenced by secp256k1::fast::field_is_zero(), secp256k1::fast::field_select(), and from_limbs_raw().
negate()
FieldElement secp256k1::fast::FieldElement::negate (unsigned = 1) const inline
Definition at line 92 of file field.hpp.
References zero().
negate_assign()
void secp256k1::fast::FieldElement::negate_assign (unsigned = 1) inline
Definition at line 95 of file field.hpp.
References zero().
one()
static FieldElement secp256k1::fast::FieldElement::one () static
operator!=()
bool secp256k1::fast::FieldElement::operator!= (const FieldElement & rhs) const inline noexcept
Definition at line 105 of file field.hpp.
operator*()
FieldElement secp256k1::fast::FieldElement::operator* (const FieldElement & rhs) const
operator*=()
FieldElement & secp256k1::fast::FieldElement::operator*= (const FieldElement & rhs)
operator+()
FieldElement secp256k1::fast::FieldElement::operator+ (const FieldElement & rhs) const
operator+=()
FieldElement & secp256k1::fast::FieldElement::operator+= (const FieldElement & rhs)
operator-()
FieldElement secp256k1::fast::FieldElement::operator- (const FieldElement & rhs) const
operator-=()
FieldElement & secp256k1::fast::FieldElement::operator-= (const FieldElement & rhs)
operator==()
bool secp256k1::fast::FieldElement::operator== (const FieldElement & rhs) const noexcept
sqrt()
FieldElement secp256k1::fast::FieldElement::sqrt () const
square()
FieldElement secp256k1::fast::FieldElement::square () const
Referenced by secp256k1::fast::fe_h_based_inversion(), and secp256k1::fast::fe_h_based_inversion_batched().
square_inplace()
void secp256k1::fast::FieldElement::square_inplace ()
to_bytes()
std::array< std::uint8_t, 32 > secp256k1::fast::FieldElement::to_bytes () const
to_bytes_into()
void secp256k1::fast::FieldElement::to_bytes_into (std::uint8_t * out) const noexcept
to_hex()
std::string secp256k1::fast::FieldElement::to_hex () const
zero()
static FieldElement secp256k1::fast::FieldElement::zero () static
Referenced by secp256k1::fast::field_cneg(), negate(), and negate_assign().
The documentation for this class was generated from the following file:
cpu/include/secp256k1/field.hpp