UltrafastSecp256k1: bench::Harness Class Reference
bench::Harness Class Reference
#include <benchmark_harness.hpp>
Public Member Functions
Harness ()=default
Harness (int warmup, std::size_t p)
template<typename Func >
double run (int iters, Func &&func) const
template<typename Func >
Stats run_stats (int iters, Func &&func) const
template<typename Func >
double run_and_print (const char *name, int iters, Func &&func) const
void print_config () const
Public Attributes
int warmup_iters = 500
std::size_t passes = 11
Detailed Description
Definition at line 285 of file benchmark_harness.hpp.
Constructor & Destructor Documentation
Harness() [1/2]
bench::Harness::Harness () default
Harness() [2/2]
bench::Harness::Harness (int warmup, std::size_t p) inline
Definition at line 291 of file benchmark_harness.hpp.
Member Function Documentation
print_config()
void bench::Harness::print_config () const inline
Definition at line 362 of file benchmark_harness.hpp.
References passes, bench::Timer::timer_name(), and warmup_iters.
run()
template<typename Func > double bench::Harness::run (int iters, Func && func) const inline
Definition at line 296 of file benchmark_harness.hpp.
References bench::ClobberMemory(), bench::compute_stats(), bench::Stats::median_ns, bench::Timer::now(), passes, bench::Timer::ticks_to_ns(), and warmup_iters.
run_and_print()
template<typename Func > double bench::Harness::run_and_print (const char * name, int iters, Func && func) const inline
Definition at line 353 of file benchmark_harness.hpp.
References bench::Stats::median_ns, bench::Stats::min_ns, bench::Stats::outliers, run_stats(), bench::Stats::samples, and bench::Stats::stddev_ns.
run_stats()
template<typename Func > Stats bench::Harness::run_stats (int iters, Func && func) const inline
Definition at line 325 of file benchmark_harness.hpp.
References bench::ClobberMemory(), bench::compute_stats(), bench::Timer::now(), passes, bench::Timer::ticks_to_ns(), and warmup_iters.
Referenced by run_and_print().
Member Data Documentation
passes
std::size_t bench::Harness::passes = 11
Definition at line 288 of file benchmark_harness.hpp.
Referenced by print_config(), run(), and run_stats().
warmup_iters
int bench::Harness::warmup_iters = 500
Definition at line 287 of file benchmark_harness.hpp.
Referenced by print_config(), run(), and run_stats().
The documentation for this class was generated from the following file:
cpu/include/secp256k1/benchmark_harness.hpp