UltrafastSecp256k1: secp256k1::ct Namespace Reference
secp256k1::ct Namespace Reference
Classes
struct CTJacobianPoint
Typedefs
using FieldElement = secp256k1::fast::FieldElement
using Point = secp256k1::fast::Point
using Scalar = secp256k1::fast::Scalar
Functions
FieldElement field_add (const FieldElement &a, const FieldElement &b) noexcept
FieldElement field_sub (const FieldElement &a, const FieldElement &b) noexcept
FieldElement field_mul (const FieldElement &a, const FieldElement &b) noexcept
FieldElement field_sqr (const FieldElement &a) noexcept
FieldElement field_neg (const FieldElement &a) noexcept
FieldElement field_inv (const FieldElement &a) noexcept
void field_cmov (FieldElement *r, const FieldElement &a, std::uint64_t mask) noexcept
void field_cswap (FieldElement *a, FieldElement *b, std::uint64_t mask) noexcept
FieldElement field_select (const FieldElement &a, const FieldElement &b, std::uint64_t mask) noexcept
FieldElement field_cneg (const FieldElement &a, std::uint64_t mask) noexcept
std::uint64_t field_is_zero (const FieldElement &a) noexcept
std::uint64_t field_eq (const FieldElement &a, const FieldElement &b) noexcept
FieldElement field_normalize (const FieldElement &a) noexcept
void value_barrier (std::uint64_t &v) noexcept
void value_barrier (std::uint32_t &v) noexcept
std::uint64_t is_zero_mask (std::uint64_t v) noexcept
std::uint64_t is_nonzero_mask (std::uint64_t v) noexcept
std::uint64_t eq_mask (std::uint64_t a, std::uint64_t b) noexcept
std::uint64_t bool_to_mask (bool flag) noexcept
std::uint64_t lt_mask (std::uint64_t a, std::uint64_t b) noexcept
void cmov64 (std::uint64_t *dst, const std::uint64_t *src, std::uint64_t mask) noexcept
void cmov256 (std::uint64_t dst[4], const std::uint64_t src[4], std::uint64_t mask) noexcept
void cswap256 (std::uint64_t a[4], std::uint64_t b[4], std::uint64_t mask) noexcept
std::uint64_t ct_select (std::uint64_t a, std::uint64_t b, std::uint64_t mask) noexcept
void ct_lookup (const void *table, std::size_t count, std::size_t stride, std::size_t index, void *out) noexcept
void ct_lookup_256 (const std::uint64_t table[][4], std::size_t count, std::size_t index, std::uint64_t out[4]) noexcept
CTJacobianPoint point_add_complete (const CTJacobianPoint &p, const CTJacobianPoint &q) noexcept
CTJacobianPoint point_dbl (const CTJacobianPoint &p) noexcept
CTJacobianPoint point_neg (const CTJacobianPoint &p) noexcept
void point_cmov (CTJacobianPoint *r, const CTJacobianPoint &a, std::uint64_t mask) noexcept
CTJacobianPoint point_select (const CTJacobianPoint &a, const CTJacobianPoint &b, std::uint64_t mask) noexcept
CTJacobianPoint point_table_lookup (const CTJacobianPoint *table, std::size_t table_size, std::size_t index) noexcept
Point scalar_mul (const Point &p, const Scalar &k) noexcept
Point generator_mul (const Scalar &k) noexcept
std::uint64_t point_is_on_curve (const Point &p) noexcept
std::uint64_t point_eq (const Point &a, const Point &b) noexcept
Scalar scalar_add (const Scalar &a, const Scalar &b) noexcept
Scalar scalar_sub (const Scalar &a, const Scalar &b) noexcept
Scalar scalar_neg (const Scalar &a) noexcept
void scalar_cmov (Scalar *r, const Scalar &a, std::uint64_t mask) noexcept
void scalar_cswap (Scalar *a, Scalar *b, std::uint64_t mask) noexcept
Scalar scalar_select (const Scalar &a, const Scalar &b, std::uint64_t mask) noexcept
Scalar scalar_cneg (const Scalar &a, std::uint64_t mask) noexcept
std::uint64_t scalar_is_zero (const Scalar &a) noexcept
std::uint64_t scalar_eq (const Scalar &a, const Scalar &b) noexcept
std::uint64_t scalar_bit (const Scalar &a, std::size_t index) noexcept
std::uint64_t scalar_window (const Scalar &a, std::size_t pos, unsigned width) noexcept
bool ct_equal (const void *a, const void *b, std::size_t len) noexcept
template<std::size_t N>
bool ct_equal (const std::array< std::uint8_t, N > &a, const std::array< std::uint8_t, N > &b) noexcept
void ct_memcpy_if (void *dst, const void *src, std::size_t len, bool flag) noexcept
void ct_memswap_if (void *a, void *b, std::size_t len, bool flag) noexcept
bool ct_is_zero (const void *data, std::size_t len) noexcept
template<std::size_t N>
bool ct_is_zero (const std::array< std::uint8_t, N > &data) noexcept
void ct_memzero (void *data, std::size_t len) noexcept
std::uint8_t ct_select_byte (std::uint8_t a, std::uint8_t b, bool flag) noexcept
int ct_compare (const void *a, const void *b, std::size_t len) noexcept
Typedef Documentation
FieldElement
typedef secp256k1::fast::FieldElement secp256k1::ct::FieldElement
Definition at line 33 of file field.hpp.
Point
using secp256k1::ct::Point = typedef secp256k1::fast::Point
Definition at line 36 of file point.hpp.
Scalar
typedef secp256k1::fast::Scalar secp256k1::ct::Scalar
Definition at line 38 of file point.hpp.
Function Documentation
bool_to_mask()
std::uint64_t secp256k1::ct::bool_to_mask (bool flag) inline noexcept
Definition at line 73 of file ops.hpp.
References value_barrier().
Referenced by ct_memcpy_if(), ct_memswap_if(), and ct_select_byte().
cmov256()
void secp256k1::ct::cmov256 (std::uint64_t dst[4], const std::uint64_t src[4], std::uint64_t mask) inline noexcept
Definition at line 102 of file ops.hpp.
cmov64()
void secp256k1::ct::cmov64 (std::uint64_t * dst, const std::uint64_t * src, std::uint64_t mask) inline noexcept
Definition at line 95 of file ops.hpp.
cswap256()
void secp256k1::ct::cswap256 (std::uint64_t a[4], std::uint64_t b[4], std::uint64_t mask) inline noexcept
Definition at line 113 of file ops.hpp.
ct_compare()
int secp256k1::ct::ct_compare (const void * a, const void * b, std::size_t len) inline noexcept
Definition at line 136 of file ct_utils.hpp.
ct_equal() [1/2]
template<std::size_t N> bool secp256k1::ct::ct_equal (const std::array< std::uint8_t, N > & a, const std::array< std::uint8_t, N > & b) inline noexcept
Definition at line 60 of file ct_utils.hpp.
References ct_equal().
ct_equal() [2/2]
bool secp256k1::ct::ct_equal (const void * a, const void * b, std::size_t len) inline noexcept
Definition at line 37 of file ct_utils.hpp.
References is_zero_mask().
Referenced by ct_equal().
ct_is_zero() [1/2]
template<std::size_t N> bool secp256k1::ct::ct_is_zero (const std::array< std::uint8_t, N > & data) inline noexcept
Definition at line 109 of file ct_utils.hpp.
References ct_is_zero().
ct_is_zero() [2/2]
bool secp256k1::ct::ct_is_zero (const void * data, std::size_t len) inline noexcept
Definition at line 99 of file ct_utils.hpp.
References is_zero_mask().
Referenced by ct_is_zero().
ct_lookup()
void secp256k1::ct::ct_lookup (const void * table, std::size_t count, std::size_t stride, std::size_t index, void * out) inline noexcept
Definition at line 136 of file ops.hpp.
References eq_mask().
ct_lookup_256()
void secp256k1::ct::ct_lookup_256 (const std::uint64_t table[][4], std::size_t count, std::size_t index, std::uint64_t out[4]) inline noexcept
Definition at line 155 of file ops.hpp.
References eq_mask().
ct_memcpy_if()
void secp256k1::ct::ct_memcpy_if (void * dst, const void * src, std::size_t len, bool flag) inline noexcept
Definition at line 67 of file ct_utils.hpp.
References bool_to_mask().
ct_memswap_if()
void secp256k1::ct::ct_memswap_if (void * a, void * b, std::size_t len, bool flag) inline noexcept
Definition at line 82 of file ct_utils.hpp.
References bool_to_mask().
ct_memzero()
void secp256k1::ct::ct_memzero (void * data, std::size_t len) inline noexcept
Definition at line 115 of file ct_utils.hpp.
ct_select()
std::uint64_t secp256k1::ct::ct_select (std::uint64_t a, std::uint64_t b, std::uint64_t mask) inline noexcept
Definition at line 125 of file ops.hpp.
ct_select_byte()
std::uint8_t secp256k1::ct::ct_select_byte (std::uint8_t a, std::uint8_t b, bool flag) inline noexcept
Definition at line 127 of file ct_utils.hpp.
References bool_to_mask().
eq_mask()
std::uint64_t secp256k1::ct::eq_mask (std::uint64_t a, std::uint64_t b) inline noexcept
Definition at line 68 of file ops.hpp.
References is_zero_mask().
Referenced by ct_lookup(), and ct_lookup_256().
field_add()
FieldElement secp256k1::ct::field_add (const FieldElement & a, const FieldElement & b) noexcept
field_cmov()
void secp256k1::ct::field_cmov (FieldElement * r, const FieldElement & a, std::uint64_t mask) noexcept
field_cneg()
FieldElement secp256k1::ct::field_cneg (const FieldElement & a, std::uint64_t mask) noexcept
field_cswap()
void secp256k1::ct::field_cswap (FieldElement * a, FieldElement * b, std::uint64_t mask) noexcept
field_eq()
std::uint64_t secp256k1::ct::field_eq (const FieldElement & a, const FieldElement & b) noexcept
field_inv()
FieldElement secp256k1::ct::field_inv (const FieldElement & a) noexcept
field_is_zero()
std::uint64_t secp256k1::ct::field_is_zero (const FieldElement & a) noexcept
field_mul()
FieldElement secp256k1::ct::field_mul (const FieldElement & a, const FieldElement & b) noexcept
field_neg()
FieldElement secp256k1::ct::field_neg (const FieldElement & a) noexcept
field_normalize()
FieldElement secp256k1::ct::field_normalize (const FieldElement & a) noexcept
field_select()
FieldElement secp256k1::ct::field_select (const FieldElement & a, const FieldElement & b, std::uint64_t mask) noexcept
field_sqr()
FieldElement secp256k1::ct::field_sqr (const FieldElement & a) noexcept
field_sub()
FieldElement secp256k1::ct::field_sub (const FieldElement & a, const FieldElement & b) noexcept
generator_mul()
Point secp256k1::ct::generator_mul (const Scalar & k) noexcept
is_nonzero_mask()
std::uint64_t secp256k1::ct::is_nonzero_mask (std::uint64_t v) inline noexcept
Definition at line 63 of file ops.hpp.
is_zero_mask()
std::uint64_t secp256k1::ct::is_zero_mask (std::uint64_t v) inline noexcept
Definition at line 54 of file ops.hpp.
References value_barrier().
Referenced by ct_equal(), ct_is_zero(), and eq_mask().
lt_mask()
std::uint64_t secp256k1::ct::lt_mask (std::uint64_t a, std::uint64_t b) inline noexcept
Definition at line 81 of file ops.hpp.
References value_barrier().
point_add_complete()
CTJacobianPoint secp256k1::ct::point_add_complete (const CTJacobianPoint & p, const CTJacobianPoint & q) noexcept
point_cmov()
void secp256k1::ct::point_cmov (CTJacobianPoint * r, const CTJacobianPoint & a, std::uint64_t mask) noexcept
point_dbl()
CTJacobianPoint secp256k1::ct::point_dbl (const CTJacobianPoint & p) noexcept
point_eq()
std::uint64_t secp256k1::ct::point_eq (const Point & a, const Point & b) noexcept
point_is_on_curve()
std::uint64_t secp256k1::ct::point_is_on_curve (const Point & p) noexcept
point_neg()
CTJacobianPoint secp256k1::ct::point_neg (const CTJacobianPoint & p) noexcept
point_select()
CTJacobianPoint secp256k1::ct::point_select (const CTJacobianPoint & a, const CTJacobianPoint & b, std::uint64_t mask) noexcept
point_table_lookup()
CTJacobianPoint secp256k1::ct::point_table_lookup (const CTJacobianPoint * table, std::size_t table_size, std::size_t index) noexcept
scalar_add()
Scalar secp256k1::ct::scalar_add (const Scalar & a, const Scalar & b) noexcept
scalar_bit()
std::uint64_t secp256k1::ct::scalar_bit (const Scalar & a, std::size_t index) noexcept
scalar_cmov()
void secp256k1::ct::scalar_cmov (Scalar * r, const Scalar & a, std::uint64_t mask) noexcept
scalar_cneg()
Scalar secp256k1::ct::scalar_cneg (const Scalar & a, std::uint64_t mask) noexcept
scalar_cswap()
void secp256k1::ct::scalar_cswap (Scalar * a, Scalar * b, std::uint64_t mask) noexcept
scalar_eq()
std::uint64_t secp256k1::ct::scalar_eq (const Scalar & a, const Scalar & b) noexcept
scalar_is_zero()
std::uint64_t secp256k1::ct::scalar_is_zero (const Scalar & a) noexcept
scalar_mul()
Point secp256k1::ct::scalar_mul (const Point & p, const Scalar & k) noexcept
scalar_neg()
Scalar secp256k1::ct::scalar_neg (const Scalar & a) noexcept
scalar_select()
Scalar secp256k1::ct::scalar_select (const Scalar & a, const Scalar & b, std::uint64_t mask) noexcept
scalar_sub()
Scalar secp256k1::ct::scalar_sub (const Scalar & a, const Scalar & b) noexcept
scalar_window()
std::uint64_t secp256k1::ct::scalar_window (const Scalar & a, std::size_t pos, unsigned width) noexcept
value_barrier() [1/2]
void secp256k1::ct::value_barrier (std::uint32_t & v) inline noexcept
Definition at line 45 of file ops.hpp.
value_barrier() [2/2]
void secp256k1::ct::value_barrier (std::uint64_t & v) inline noexcept
Definition at line 41 of file ops.hpp.
Referenced by bool_to_mask(), is_zero_mask(), and lt_mask().