UltrafastSecp256k1: secp256k1::fast::debug Namespace Reference
secp256k1::fast::debug Namespace Reference
Classes
struct DebugCounters
Functions
bool is_normalized_field_element (const FieldElement &fe) noexcept
bool is_on_curve (const Point &pt) noexcept
bool is_valid_scalar (const Scalar &s) noexcept
DebugCounters & counters () noexcept
Function Documentation
counters()
DebugCounters & secp256k1::fast::debug::counters () inline noexcept
Definition at line 171 of file debug_invariants.hpp.
is_normalized_field_element()
bool secp256k1::fast::debug::is_normalized_field_element (const FieldElement & fe) inline noexcept
Definition at line 63 of file debug_invariants.hpp.
is_on_curve()
bool secp256k1::fast::debug::is_on_curve (const Point & pt) inline noexcept
Definition at line 84 of file debug_invariants.hpp.
References secp256k1::fast::FieldElement::from_uint64(), secp256k1::fast::FieldElement52::n, secp256k1::fast::FieldElement::square(), secp256k1::fast::FieldElement52::square(), and secp256k1::fast::FieldElement::zero().
is_valid_scalar()
bool secp256k1::fast::debug::is_valid_scalar (const Scalar & s) inline noexcept
Definition at line 137 of file debug_invariants.hpp.
References secp256k1::fast::FieldElement52::is_zero().