UltrafastSecp256k1: secp256k1::simd Namespace Reference
secp256k1::simd Namespace Reference
Namespaces
namespace detail
Enumerations
enum class SimdTier : int { SCALAR = 0 , AVX2 = 1 , AVX512 = 2 }
Functions
bool avx2_available () noexcept
bool avx512_available () noexcept
SimdTier detect_simd_tier () noexcept
const char * simd_tier_name (SimdTier tier) noexcept
void batch_field_add (FieldElement *out, const FieldElement *a, const FieldElement *b, std::size_t count)
void batch_field_sub (FieldElement *out, const FieldElement *a, const FieldElement *b, std::size_t count)
void batch_field_mul (FieldElement *out, const FieldElement *a, const FieldElement *b, std::size_t count)
void batch_field_sqr (FieldElement *out, const FieldElement *a, std::size_t count)
void batch_field_inv (FieldElement *out, const FieldElement *a, std::size_t count, FieldElement *scratch=nullptr)
Enumeration Type Documentation
SimdTier
enum class secp256k1::simd::SimdTier : int strong
Enumerator
SCALAR
AVX2
AVX512
Definition at line 90 of file field_simd.hpp.
Function Documentation
avx2_available()
bool secp256k1::simd::avx2_available () inline noexcept
Definition at line 51 of file field_simd.hpp.
Referenced by detect_simd_tier().
avx512_available()
bool secp256k1::simd::avx512_available () inline noexcept
Definition at line 70 of file field_simd.hpp.
Referenced by detect_simd_tier().
batch_field_add()
void secp256k1::simd::batch_field_add (FieldElement * out, const FieldElement * a, const FieldElement * b, std::size_t count)
batch_field_inv()
void secp256k1::simd::batch_field_inv (FieldElement * out, const FieldElement * a, std::size_t count, FieldElement * scratch = nullptr)
batch_field_mul()
void secp256k1::simd::batch_field_mul (FieldElement * out, const FieldElement * a, const FieldElement * b, std::size_t count)
batch_field_sqr()
void secp256k1::simd::batch_field_sqr (FieldElement * out, const FieldElement * a, std::size_t count)
batch_field_sub()
void secp256k1::simd::batch_field_sub (FieldElement * out, const FieldElement * a, const FieldElement * b, std::size_t count)
detect_simd_tier()
SimdTier secp256k1::simd::detect_simd_tier () inline noexcept
Definition at line 97 of file field_simd.hpp.
References AVX2, avx2_available(), AVX512, avx512_available(), and SCALAR.
simd_tier_name()
const char * secp256k1::simd::simd_tier_name (SimdTier tier) inline noexcept
Definition at line 103 of file field_simd.hpp.
References AVX2, and AVX512.