UltrafastSecp256k1: bench Namespace Reference
bench Namespace Reference
Classes
class Harness
struct Stats
struct Timer
Functions
template<typename T >
void DoNotOptimize (T const &value)
template<typename T >
void DoNotOptimize (T &value)
void ClobberMemory ()
Stats compute_stats (std::vector< double > &data)
void pin_thread_and_elevate ()
const char * format_ns (double ns, char *buf, std::size_t buflen)
const char * format_ns (double ns)
Function Documentation
ClobberMemory()
void bench::ClobberMemory () inline
Definition at line 97 of file benchmark_harness.hpp.
Referenced by bench::Harness::run(), and bench::Harness::run_stats().
compute_stats()
Stats bench::compute_stats (std::vector< double > & data) inline
Definition at line 205 of file benchmark_harness.hpp.
Referenced by bench::Harness::run(), and bench::Harness::run_stats().
DoNotOptimize() [1/2]
template<typename T > void bench::DoNotOptimize (T & value) inline
Definition at line 92 of file benchmark_harness.hpp.
DoNotOptimize() [2/2]
template<typename T > void bench::DoNotOptimize (T const & value) inline
Definition at line 86 of file benchmark_harness.hpp.
format_ns() [1/2]
const char * bench::format_ns (double ns) inline
Definition at line 383 of file benchmark_harness.hpp.
References format_ns().
format_ns() [2/2]
const char * bench::format_ns (double ns, char * buf, std::size_t buflen) inline
Definition at line 371 of file benchmark_harness.hpp.
Referenced by format_ns().
pin_thread_and_elevate()
void bench::pin_thread_and_elevate () inline
Definition at line 269 of file benchmark_harness.hpp.