UltrafastSecp256k1: secp256k1 Namespace Reference
secp256k1 Namespace Reference
Namespaces
namespace coins
namespace ct
namespace detail
namespace fast
namespace hash
namespace simd
namespace test
Classes
struct AffinePointData
struct Bech32DecodeResult
struct CurveContext
struct ECDSAAdaptorSig
struct ECDSABatchEntry
struct ECDSASignature
struct ExtendedKey
struct FieldElementData
struct FrostCommitment
struct FrostKeyPackage
struct FrostNonce
struct FrostNonceCommitment
struct FrostPartialSig
struct FrostShare
struct JacobianPointData
struct MidFieldElementData
struct MuSig2AggNonce
struct MuSig2KeyAggCtx
struct MuSig2PubNonce
struct MuSig2SecNonce
struct MuSig2Session
struct PedersenCommitment
struct RecoverableSignature
struct ScalarData
struct SchnorrAdaptorSig
struct SchnorrBatchEntry
struct SchnorrKeypair
struct SchnorrSignature
struct SchnorrXonlyPubkey
class SHA256
class SHA512
struct SilentPaymentAddress
struct WIFDecodeResult
Typedefs
using ParticipantId = std::uint32_t
Enumerations
enum class Network : std::uint8_t { Mainnet = 0 , Testnet = 1 }
enum class Bech32Encoding { BECH32 , BECH32M }
Functions
SchnorrAdaptorSig schnorr_adaptor_sign (const fast::Scalar &private_key, const std::array< std::uint8_t, 32 > &msg, const fast::Point &adaptor_point, const std::array< std::uint8_t, 32 > &aux_rand)
bool schnorr_adaptor_verify (const SchnorrAdaptorSig &pre_sig, const std::array< std::uint8_t, 32 > &pubkey_x, const std::array< std::uint8_t, 32 > &msg, const fast::Point &adaptor_point)
SchnorrSignature schnorr_adaptor_adapt (const SchnorrAdaptorSig &pre_sig, const fast::Scalar &adaptor_secret)
std::pair< fast::Scalar, bool > schnorr_adaptor_extract (const SchnorrAdaptorSig &pre_sig, const SchnorrSignature &sig)
ECDSAAdaptorSig ecdsa_adaptor_sign (const fast::Scalar &private_key, const std::array< std::uint8_t, 32 > &msg_hash, const fast::Point &adaptor_point)
bool ecdsa_adaptor_verify (const ECDSAAdaptorSig &pre_sig, const fast::Point &public_key, const std::array< std::uint8_t, 32 > &msg_hash, const fast::Point &adaptor_point)
ECDSASignature ecdsa_adaptor_adapt (const ECDSAAdaptorSig &pre_sig, const fast::Scalar &adaptor_secret)
std::pair< fast::Scalar, bool > ecdsa_adaptor_extract (const ECDSAAdaptorSig &pre_sig, const ECDSASignature &sig)
std::string base58check_encode (const std::uint8_t *data, std::size_t len)
std::pair< std::vector< std::uint8_t >, bool > base58check_decode (const std::string &encoded)
std::string bech32_encode (const std::string &hrp, std::uint8_t witness_version, const std::uint8_t *witness_program, std::size_t prog_len)
Bech32DecodeResult bech32_decode (const std::string &addr)
std::array< std::uint8_t, 20 > hash160 (const std::uint8_t *data, std::size_t len)
std::string address_p2pkh (const fast::Point &pubkey, Network net=Network::Mainnet)
std::string address_p2wpkh (const fast::Point &pubkey, Network net=Network::Mainnet)
std::string address_p2tr (const fast::Point &internal_key, Network net=Network::Mainnet)
std::string address_p2tr_raw (const std::array< std::uint8_t, 32 > &output_key_x, Network net=Network::Mainnet)
std::string wif_encode (const fast::Scalar &private_key, bool compressed=true, Network net=Network::Mainnet)
WIFDecodeResult wif_decode (const std::string &wif)
SilentPaymentAddress silent_payment_address (const fast::Scalar &scan_privkey, const fast::Scalar &spend_privkey)
std::pair< fast::Point, fast::Scalar > silent_payment_create_output (const std::vector< fast::Scalar > &input_privkeys, const SilentPaymentAddress &recipient, std::uint32_t k=0)
std::vector< std::pair< std::uint32_t, fast::Scalar > > silent_payment_scan (const fast::Scalar &scan_privkey, const fast::Scalar &spend_privkey, const std::vector< fast::Point > &input_pubkeys, const std::vector< std::array< std::uint8_t, 32 > > &output_pubkeys)
bool schnorr_batch_verify (const SchnorrBatchEntry *entries, std::size_t n)
bool schnorr_batch_verify (const std::vector< SchnorrBatchEntry > &entries)
bool ecdsa_batch_verify (const ECDSABatchEntry *entries, std::size_t n)
bool ecdsa_batch_verify (const std::vector< ECDSABatchEntry > &entries)
std::vector< std::size_t > schnorr_batch_identify_invalid (const SchnorrBatchEntry *entries, std::size_t n)
std::vector< std::size_t > ecdsa_batch_identify_invalid (const ECDSABatchEntry *entries, std::size_t n)
std::pair< ExtendedKey, bool > bip32_master_key (const std::uint8_t *seed, std::size_t seed_len)
std::pair< ExtendedKey, bool > bip32_derive_path (const ExtendedKey &master, const std::string &path)
std::array< std::uint8_t, 64 > hmac_sha512 (const std::uint8_t *key, std::size_t key_len, const std::uint8_t *data, std::size_t data_len)
const fast::Point & effective_generator (const CurveContext *ctx=nullptr)
fast::Point derive_public_key (const fast::Scalar &private_key, const CurveContext *ctx=nullptr)
fast::Point scalar_mul_G (const fast::Scalar &scalar, const CurveContext *ctx=nullptr)
std::array< std::uint8_t, 32 > ecdh_compute (const Scalar &private_key, const Point &public_key)
std::array< std::uint8_t, 32 > ecdh_compute_xonly (const Scalar &private_key, const Point &public_key)
std::array< std::uint8_t, 32 > ecdh_compute_raw (const Scalar &private_key, const Point &public_key)
ECDSASignature ecdsa_sign (const std::array< std::uint8_t, 32 > &msg_hash, const fast::Scalar &private_key)
bool ecdsa_verify (const std::array< std::uint8_t, 32 > &msg_hash, const fast::Point &public_key, const ECDSASignature &sig)
fast::Scalar rfc6979_nonce (const fast::Scalar &private_key, const std::array< std::uint8_t, 32 > &msg_hash)
std::pair< FrostCommitment, std::vector< FrostShare > > frost_keygen_begin (ParticipantId participant_id, std::uint32_t threshold, std::uint32_t num_participants, const std::array< std::uint8_t, 32 > &secret_seed)
std::pair< FrostKeyPackage, bool > frost_keygen_finalize (ParticipantId participant_id, const std::vector< FrostCommitment > &commitments, const std::vector< FrostShare > &received_shares, std::uint32_t threshold, std::uint32_t num_participants)
std::pair< FrostNonce, FrostNonceCommitment > frost_sign_nonce_gen (ParticipantId participant_id, const std::array< std::uint8_t, 32 > &nonce_seed)
FrostPartialSig frost_sign (const FrostKeyPackage &key_pkg, const FrostNonce &nonce, const std::array< std::uint8_t, 32 > &msg, const std::vector< FrostNonceCommitment > &nonce_commitments)
bool frost_verify_partial (const FrostPartialSig &partial_sig, const FrostNonceCommitment &signer_commitment, const fast::Point &verification_share, const std::array< std::uint8_t, 32 > &msg, const std::vector< FrostNonceCommitment > &nonce_commitments, const fast::Point &group_public_key)
SchnorrSignature frost_aggregate (const std::vector< FrostPartialSig > &partial_sigs, const std::vector< FrostNonceCommitment > &nonce_commitments, const fast::Point &group_public_key, const std::array< std::uint8_t, 32 > &msg)
fast::Scalar frost_lagrange_coefficient (ParticipantId i, const std::vector< ParticipantId > &signer_ids)
fast::Point shamir_trick (const fast::Scalar &a, const fast::Point &P, const fast::Scalar &b, const fast::Point &Q)
fast::Point multi_scalar_mul (const fast::Scalar *scalars, const fast::Point *points, std::size_t n)
fast::Point multi_scalar_mul (const std::vector< fast::Scalar > &scalars, const std::vector< fast::Point > &points)
unsigned strauss_optimal_window (std::size_t n)
MuSig2KeyAggCtx musig2_key_agg (const std::vector< std::array< std::uint8_t, 32 > > &pubkeys)
std::pair< MuSig2SecNonce, MuSig2PubNonce > musig2_nonce_gen (const fast::Scalar &secret_key, const std::array< std::uint8_t, 32 > &pub_key, const std::array< std::uint8_t, 32 > &agg_pub_key, const std::array< std::uint8_t, 32 > &msg, const std::uint8_t *extra_input=nullptr)
MuSig2AggNonce musig2_nonce_agg (const std::vector< MuSig2PubNonce > &pub_nonces)
MuSig2Session musig2_start_sign_session (const MuSig2AggNonce &agg_nonce, const MuSig2KeyAggCtx &key_agg_ctx, const std::array< std::uint8_t, 32 > &msg)
fast::Scalar musig2_partial_sign (const MuSig2SecNonce &sec_nonce, const fast::Scalar &secret_key, const MuSig2KeyAggCtx &key_agg_ctx, const MuSig2Session &session, std::size_t signer_index)
bool musig2_partial_verify (const fast::Scalar &partial_sig, const MuSig2PubNonce &pub_nonce, const std::array< std::uint8_t, 32 > &pubkey, const MuSig2KeyAggCtx &key_agg_ctx, const MuSig2Session &session, std::size_t signer_index)
std::array< std::uint8_t, 64 > musig2_partial_sig_agg (const std::vector< fast::Scalar > &partial_sigs, const MuSig2Session &session)
const fast::Point & pedersen_generator_H ()
PedersenCommitment pedersen_commit (const fast::Scalar &value, const fast::Scalar &blinding)
bool pedersen_verify (const PedersenCommitment &commitment, const fast::Scalar &value, const fast::Scalar &blinding)
bool pedersen_verify_sum (const PedersenCommitment *commitments_pos, std::size_t n_pos, const PedersenCommitment *commitments_neg, std::size_t n_neg)
fast::Scalar pedersen_blind_sum (const fast::Scalar *blinds_in, std::size_t n_in, const fast::Scalar *blinds_out, std::size_t n_out)
const fast::Point & pedersen_generator_J ()
PedersenCommitment pedersen_switch_commit (const fast::Scalar &value, const fast::Scalar &blinding, const fast::Scalar &switch_blind)
fast::Point pippenger_msm (const fast::Scalar *scalars, const fast::Point *points, std::size_t n)
fast::Point pippenger_msm (const std::vector< fast::Scalar > &scalars, const std::vector< fast::Point > &points)
unsigned pippenger_optimal_window (std::size_t n)
fast::Point msm (const fast::Scalar *scalars, const fast::Point *points, std::size_t n)
fast::Point msm (const std::vector< fast::Scalar > &scalars, const std::vector< fast::Point > &points)
RecoverableSignature ecdsa_sign_recoverable (const std::array< std::uint8_t, 32 > &msg_hash, const Scalar &private_key)
std::pair< Point, bool > ecdsa_recover (const std::array< std::uint8_t, 32 > &msg_hash, const ECDSASignature &sig, int recid)
std::array< std::uint8_t, 65 > recoverable_to_compact (const RecoverableSignature &rsig, bool compressed=true)
std::pair< RecoverableSignature, bool > recoverable_from_compact (const std::array< std::uint8_t, 65 > &data)
SchnorrKeypair schnorr_keypair_create (const fast::Scalar &private_key)
SchnorrSignature schnorr_sign (const SchnorrKeypair &kp, const std::array< std::uint8_t, 32 > &msg, const std::array< std::uint8_t, 32 > &aux_rand)
SchnorrSignature schnorr_sign (const fast::Scalar &private_key, const std::array< std::uint8_t, 32 > &msg, const std::array< std::uint8_t, 32 > &aux_rand)
bool schnorr_verify (const std::array< std::uint8_t, 32 > &pubkey_x, const std::array< std::uint8_t, 32 > &msg, const SchnorrSignature &sig)
bool schnorr_xonly_pubkey_parse (SchnorrXonlyPubkey &out, const std::array< std::uint8_t, 32 > &pubkey_x)
SchnorrXonlyPubkey schnorr_xonly_from_keypair (const SchnorrKeypair &kp)
bool schnorr_verify (const SchnorrXonlyPubkey &pubkey, const std::array< std::uint8_t, 32 > &msg, const SchnorrSignature &sig)
std::array< std::uint8_t, 32 > tagged_hash (const char *tag, const void *data, std::size_t len)
std::array< std::uint8_t, 32 > schnorr_pubkey (const fast::Scalar &private_key)
std::array< std::uint8_t, 32 > taproot_tweak_hash (const std::array< std::uint8_t, 32 > &internal_key_x, const std::uint8_t *merkle_root=nullptr, std::size_t merkle_root_len=0)
std::array< std::uint8_t, 32 > taproot_leaf_hash (const std::uint8_t *script, std::size_t script_len, std::uint8_t leaf_version=0xC0)
std::array< std::uint8_t, 32 > taproot_branch_hash (const std::array< std::uint8_t, 32 > &a, const std::array< std::uint8_t, 32 > &b)
std::pair< std::array< std::uint8_t, 32 >, int > taproot_output_key (const std::array< std::uint8_t, 32 > &internal_key_x, const std::uint8_t *merkle_root=nullptr, std::size_t merkle_root_len=0)
Scalar taproot_tweak_privkey (const Scalar &private_key, const std::uint8_t *merkle_root=nullptr, std::size_t merkle_root_len=0)
bool taproot_verify_commitment (const std::array< std::uint8_t, 32 > &output_key_x, int output_key_parity, const std::array< std::uint8_t, 32 > &internal_key_x, const std::uint8_t *merkle_root=nullptr, std::size_t merkle_root_len=0)
std::array< std::uint8_t, 32 > taproot_merkle_root_from_proof (const std::array< std::uint8_t, 32 > &leaf_hash, const std::vector< std::array< std::uint8_t, 32 > > &proof)
std::array< std::uint8_t, 32 > taproot_merkle_root (const std::vector< std::array< std::uint8_t, 32 > > &leaf_hashes)
FieldElementData * fe_to_data (void *fe) noexcept
const FieldElementData * fe_to_data (const void *fe) noexcept
ScalarData * sc_to_data (void *sc) noexcept
const ScalarData * sc_to_data (const void *sc) noexcept
Typedef Documentation
ParticipantId
using secp256k1::ParticipantId = typedef std::uint32_t
Definition at line 39 of file frost.hpp.
Enumeration Type Documentation
Bech32Encoding
enum class secp256k1::Bech32Encoding strong
Enumerator
BECH32
BECH32M
Definition at line 52 of file address.hpp.
Network
enum class secp256k1::Network : std::uint8_t strong
Enumerator
Mainnet
Testnet
Definition at line 36 of file address.hpp.
Function Documentation
address_p2pkh()
std::string secp256k1::address_p2pkh (const fast::Point & pubkey, Network net = Network::Mainnet)
Referenced by ufsecp_addr_p2pkh().
address_p2tr()
std::string secp256k1::address_p2tr (const fast::Point & internal_key, Network net = Network::Mainnet)
address_p2tr_raw()
std::string secp256k1::address_p2tr_raw (const std::array< std::uint8_t, 32 > & output_key_x, Network net = Network::Mainnet)
Referenced by ufsecp_addr_p2tr().
address_p2wpkh()
std::string secp256k1::address_p2wpkh (const fast::Point & pubkey, Network net = Network::Mainnet)
Referenced by ufsecp_addr_p2wpkh().
base58check_decode()
std::pair< std::vector< std::uint8_t >, bool > secp256k1::base58check_decode (const std::string & encoded)
base58check_encode()
std::string secp256k1::base58check_encode (const std::uint8_t * data, std::size_t len)
bech32_decode()
Bech32DecodeResult secp256k1::bech32_decode (const std::string & addr)
bech32_encode()
std::string secp256k1::bech32_encode (const std::string & hrp, std::uint8_t witness_version, const std::uint8_t * witness_program, std::size_t prog_len)
bip32_derive_path()
std::pair< ExtendedKey, bool > secp256k1::bip32_derive_path (const ExtendedKey & master, const std::string & path)
Referenced by ufsecp_bip32_derive_path().
bip32_master_key()
std::pair< ExtendedKey, bool > secp256k1::bip32_master_key (const std::uint8_t * seed, std::size_t seed_len)
Referenced by ufsecp_bip32_master().
derive_public_key()
fast::Point secp256k1::derive_public_key (const fast::Scalar & private_key, const CurveContext * ctx = nullptr) inline
Definition at line 125 of file context.hpp.
References effective_generator(), and secp256k1::fast::Point::scalar_mul().
ecdh_compute()
std::array< std::uint8_t, 32 > secp256k1::ecdh_compute (const Scalar & private_key, const Point & public_key)
Referenced by ufsecp_ecdh().
ecdh_compute_raw()
std::array< std::uint8_t, 32 > secp256k1::ecdh_compute_raw (const Scalar & private_key, const Point & public_key)
Referenced by ufsecp_ecdh_raw().
ecdh_compute_xonly()
std::array< std::uint8_t, 32 > secp256k1::ecdh_compute_xonly (const Scalar & private_key, const Point & public_key)
Referenced by ufsecp_ecdh_xonly().
ecdsa_adaptor_adapt()
ECDSASignature secp256k1::ecdsa_adaptor_adapt (const ECDSAAdaptorSig & pre_sig, const fast::Scalar & adaptor_secret)
ecdsa_adaptor_extract()
std::pair< fast::Scalar, bool > secp256k1::ecdsa_adaptor_extract (const ECDSAAdaptorSig & pre_sig, const ECDSASignature & sig)
ecdsa_adaptor_sign()
ECDSAAdaptorSig secp256k1::ecdsa_adaptor_sign (const fast::Scalar & private_key, const std::array< std::uint8_t, 32 > & msg_hash, const fast::Point & adaptor_point)
ecdsa_adaptor_verify()
bool secp256k1::ecdsa_adaptor_verify (const ECDSAAdaptorSig & pre_sig, const fast::Point & public_key, const std::array< std::uint8_t, 32 > & msg_hash, const fast::Point & adaptor_point)
ecdsa_batch_identify_invalid()
std::vector< std::size_t > secp256k1::ecdsa_batch_identify_invalid (const ECDSABatchEntry * entries, std::size_t n)
ecdsa_batch_verify() [1/2]
bool secp256k1::ecdsa_batch_verify (const ECDSABatchEntry * entries, std::size_t n)
ecdsa_batch_verify() [2/2]
bool secp256k1::ecdsa_batch_verify (const std::vector< ECDSABatchEntry > & entries)
ecdsa_recover()
std::pair< Point, bool > secp256k1::ecdsa_recover (const std::array< std::uint8_t, 32 > & msg_hash, const ECDSASignature & sig, int recid)
Referenced by ufsecp_ecdsa_recover().
ecdsa_sign()
ECDSASignature secp256k1::ecdsa_sign (const std::array< std::uint8_t, 32 > & msg_hash, const fast::Scalar & private_key)
Referenced by ufsecp_ecdsa_sign().
ecdsa_sign_recoverable()
RecoverableSignature secp256k1::ecdsa_sign_recoverable (const std::array< std::uint8_t, 32 > & msg_hash, const Scalar & private_key)
Referenced by ufsecp_ecdsa_sign_recoverable().
ecdsa_verify()
bool secp256k1::ecdsa_verify (const std::array< std::uint8_t, 32 > & msg_hash, const fast::Point & public_key, const ECDSASignature & sig)
Referenced by ufsecp_ecdsa_verify().
effective_generator()
const fast::Point & secp256k1::effective_generator (const CurveContext * ctx = nullptr) inline
Definition at line 116 of file context.hpp.
References secp256k1::CurveContext::generator, and secp256k1::fast::Point::generator().
Referenced by derive_public_key(), and scalar_mul_G().
fe_to_data() [1/2]
const FieldElementData * secp256k1::fe_to_data (const void * fe) inline noexcept
Definition at line 108 of file types.hpp.
fe_to_data() [2/2]
FieldElementData * secp256k1::fe_to_data (void * fe) inline noexcept
Definition at line 104 of file types.hpp.
frost_aggregate()
SchnorrSignature secp256k1::frost_aggregate (const std::vector< FrostPartialSig > & partial_sigs, const std::vector< FrostNonceCommitment > & nonce_commitments, const fast::Point & group_public_key, const std::array< std::uint8_t, 32 > & msg)
frost_keygen_begin()
std::pair< FrostCommitment, std::vector< FrostShare > > secp256k1::frost_keygen_begin (ParticipantId participant_id, std::uint32_t threshold, std::uint32_t num_participants, const std::array< std::uint8_t, 32 > & secret_seed)
frost_keygen_finalize()
std::pair< FrostKeyPackage, bool > secp256k1::frost_keygen_finalize (ParticipantId participant_id, const std::vector< FrostCommitment > & commitments, const std::vector< FrostShare > & received_shares, std::uint32_t threshold, std::uint32_t num_participants)
frost_lagrange_coefficient()
fast::Scalar secp256k1::frost_lagrange_coefficient (ParticipantId i, const std::vector< ParticipantId > & signer_ids)
frost_sign()
FrostPartialSig secp256k1::frost_sign (const FrostKeyPackage & key_pkg, const FrostNonce & nonce, const std::array< std::uint8_t, 32 > & msg, const std::vector< FrostNonceCommitment > & nonce_commitments)
frost_sign_nonce_gen()
std::pair< FrostNonce, FrostNonceCommitment > secp256k1::frost_sign_nonce_gen (ParticipantId participant_id, const std::array< std::uint8_t, 32 > & nonce_seed)
frost_verify_partial()
bool secp256k1::frost_verify_partial (const FrostPartialSig & partial_sig, const FrostNonceCommitment & signer_commitment, const fast::Point & verification_share, const std::array< std::uint8_t, 32 > & msg, const std::vector< FrostNonceCommitment > & nonce_commitments, const fast::Point & group_public_key)
hash160()
std::array< std::uint8_t, 20 > secp256k1::hash160 (const std::uint8_t * data, std::size_t len)
Referenced by ufsecp_hash160().
hmac_sha512()
std::array< std::uint8_t, 64 > secp256k1::hmac_sha512 (const std::uint8_t * key, std::size_t key_len, const std::uint8_t * data, std::size_t data_len)
msm() [1/2]
fast::Point secp256k1::msm (const fast::Scalar * scalars, const fast::Point * points, std::size_t n)
msm() [2/2]
fast::Point secp256k1::msm (const std::vector< fast::Scalar > & scalars, const std::vector< fast::Point > & points)
multi_scalar_mul() [1/2]
fast::Point secp256k1::multi_scalar_mul (const fast::Scalar * scalars, const fast::Point * points, std::size_t n)
multi_scalar_mul() [2/2]
fast::Point secp256k1::multi_scalar_mul (const std::vector< fast::Scalar > & scalars, const std::vector< fast::Point > & points)
musig2_key_agg()
MuSig2KeyAggCtx secp256k1::musig2_key_agg (const std::vector< std::array< std::uint8_t, 32 > > & pubkeys)
musig2_nonce_agg()
MuSig2AggNonce secp256k1::musig2_nonce_agg (const std::vector< MuSig2PubNonce > & pub_nonces)
musig2_nonce_gen()
std::pair< MuSig2SecNonce, MuSig2PubNonce > secp256k1::musig2_nonce_gen (const fast::Scalar & secret_key, const std::array< std::uint8_t, 32 > & pub_key, const std::array< std::uint8_t, 32 > & agg_pub_key, const std::array< std::uint8_t, 32 > & msg, const std::uint8_t * extra_input = nullptr)
musig2_partial_sig_agg()
std::array< std::uint8_t, 64 > secp256k1::musig2_partial_sig_agg (const std::vector< fast::Scalar > & partial_sigs, const MuSig2Session & session)
musig2_partial_sign()
fast::Scalar secp256k1::musig2_partial_sign (const MuSig2SecNonce & sec_nonce, const fast::Scalar & secret_key, const MuSig2KeyAggCtx & key_agg_ctx, const MuSig2Session & session, std::size_t signer_index)
musig2_partial_verify()
bool secp256k1::musig2_partial_verify (const fast::Scalar & partial_sig, const MuSig2PubNonce & pub_nonce, const std::array< std::uint8_t, 32 > & pubkey, const MuSig2KeyAggCtx & key_agg_ctx, const MuSig2Session & session, std::size_t signer_index)
musig2_start_sign_session()
MuSig2Session secp256k1::musig2_start_sign_session (const MuSig2AggNonce & agg_nonce, const MuSig2KeyAggCtx & key_agg_ctx, const std::array< std::uint8_t, 32 > & msg)
pedersen_blind_sum()
fast::Scalar secp256k1::pedersen_blind_sum (const fast::Scalar * blinds_in, std::size_t n_in, const fast::Scalar * blinds_out, std::size_t n_out)
pedersen_commit()
PedersenCommitment secp256k1::pedersen_commit (const fast::Scalar & value, const fast::Scalar & blinding)
pedersen_generator_H()
const fast::Point & secp256k1::pedersen_generator_H ()
pedersen_generator_J()
const fast::Point & secp256k1::pedersen_generator_J ()
pedersen_switch_commit()
PedersenCommitment secp256k1::pedersen_switch_commit (const fast::Scalar & value, const fast::Scalar & blinding, const fast::Scalar & switch_blind)
pedersen_verify()
bool secp256k1::pedersen_verify (const PedersenCommitment & commitment, const fast::Scalar & value, const fast::Scalar & blinding)
pedersen_verify_sum()
bool secp256k1::pedersen_verify_sum (const PedersenCommitment * commitments_pos, std::size_t n_pos, const PedersenCommitment * commitments_neg, std::size_t n_neg)
pippenger_msm() [1/2]
fast::Point secp256k1::pippenger_msm (const fast::Scalar * scalars, const fast::Point * points, std::size_t n)
pippenger_msm() [2/2]
fast::Point secp256k1::pippenger_msm (const std::vector< fast::Scalar > & scalars, const std::vector< fast::Point > & points)
pippenger_optimal_window()
unsigned secp256k1::pippenger_optimal_window (std::size_t n)
recoverable_from_compact()
std::pair< RecoverableSignature, bool > secp256k1::recoverable_from_compact (const std::array< std::uint8_t, 65 > & data)
recoverable_to_compact()
std::array< std::uint8_t, 65 > secp256k1::recoverable_to_compact (const RecoverableSignature & rsig, bool compressed = true)
rfc6979_nonce()
fast::Scalar secp256k1::rfc6979_nonce (const fast::Scalar & private_key, const std::array< std::uint8_t, 32 > & msg_hash)
sc_to_data() [1/2]
const ScalarData * secp256k1::sc_to_data (const void * sc) inline noexcept
Definition at line 116 of file types.hpp.
sc_to_data() [2/2]
ScalarData * secp256k1::sc_to_data (void * sc) inline noexcept
Definition at line 112 of file types.hpp.
scalar_mul_G()
fast::Point secp256k1::scalar_mul_G (const fast::Scalar & scalar, const CurveContext * ctx = nullptr) inline
Definition at line 131 of file context.hpp.
References effective_generator(), and secp256k1::fast::Point::scalar_mul().
schnorr_adaptor_adapt()
SchnorrSignature secp256k1::schnorr_adaptor_adapt (const SchnorrAdaptorSig & pre_sig, const fast::Scalar & adaptor_secret)
schnorr_adaptor_extract()
std::pair< fast::Scalar, bool > secp256k1::schnorr_adaptor_extract (const SchnorrAdaptorSig & pre_sig, const SchnorrSignature & sig)
schnorr_adaptor_sign()
SchnorrAdaptorSig secp256k1::schnorr_adaptor_sign (const fast::Scalar & private_key, const std::array< std::uint8_t, 32 > & msg, const fast::Point & adaptor_point, const std::array< std::uint8_t, 32 > & aux_rand)
schnorr_adaptor_verify()
bool secp256k1::schnorr_adaptor_verify (const SchnorrAdaptorSig & pre_sig, const std::array< std::uint8_t, 32 > & pubkey_x, const std::array< std::uint8_t, 32 > & msg, const fast::Point & adaptor_point)
schnorr_batch_identify_invalid()
std::vector< std::size_t > secp256k1::schnorr_batch_identify_invalid (const SchnorrBatchEntry * entries, std::size_t n)
schnorr_batch_verify() [1/2]
bool secp256k1::schnorr_batch_verify (const SchnorrBatchEntry * entries, std::size_t n)
schnorr_batch_verify() [2/2]
bool secp256k1::schnorr_batch_verify (const std::vector< SchnorrBatchEntry > & entries)
schnorr_keypair_create()
SchnorrKeypair secp256k1::schnorr_keypair_create (const fast::Scalar & private_key)
schnorr_pubkey()
std::array< std::uint8_t, 32 > secp256k1::schnorr_pubkey (const fast::Scalar & private_key)
Referenced by ufsecp_pubkey_xonly().
schnorr_sign() [1/2]
SchnorrSignature secp256k1::schnorr_sign (const fast::Scalar & private_key, const std::array< std::uint8_t, 32 > & msg, const std::array< std::uint8_t, 32 > & aux_rand)
schnorr_sign() [2/2]
SchnorrSignature secp256k1::schnorr_sign (const SchnorrKeypair & kp, const std::array< std::uint8_t, 32 > & msg, const std::array< std::uint8_t, 32 > & aux_rand)
Referenced by ufsecp_schnorr_sign().
schnorr_verify() [1/2]
bool secp256k1::schnorr_verify (const SchnorrXonlyPubkey & pubkey, const std::array< std::uint8_t, 32 > & msg, const SchnorrSignature & sig)
schnorr_verify() [2/2]
bool secp256k1::schnorr_verify (const std::array< std::uint8_t, 32 > & pubkey_x, const std::array< std::uint8_t, 32 > & msg, const SchnorrSignature & sig)
Referenced by ufsecp_schnorr_verify().
schnorr_xonly_from_keypair()
SchnorrXonlyPubkey secp256k1::schnorr_xonly_from_keypair (const SchnorrKeypair & kp)
schnorr_xonly_pubkey_parse()
bool secp256k1::schnorr_xonly_pubkey_parse (SchnorrXonlyPubkey & out, const std::array< std::uint8_t, 32 > & pubkey_x)
shamir_trick()
fast::Point secp256k1::shamir_trick (const fast::Scalar & a, const fast::Point & P, const fast::Scalar & b, const fast::Point & Q)
silent_payment_address()
SilentPaymentAddress secp256k1::silent_payment_address (const fast::Scalar & scan_privkey, const fast::Scalar & spend_privkey)
silent_payment_create_output()
std::pair< fast::Point, fast::Scalar > secp256k1::silent_payment_create_output (const std::vector< fast::Scalar > & input_privkeys, const SilentPaymentAddress & recipient, std::uint32_t k = 0)
silent_payment_scan()
std::vector< std::pair< std::uint32_t, fast::Scalar > > secp256k1::silent_payment_scan (const fast::Scalar & scan_privkey, const fast::Scalar & spend_privkey, const std::vector< fast::Point > & input_pubkeys, const std::vector< std::array< std::uint8_t, 32 > > & output_pubkeys)
strauss_optimal_window()
unsigned secp256k1::strauss_optimal_window (std::size_t n)
tagged_hash()
std::array< std::uint8_t, 32 > secp256k1::tagged_hash (const char * tag, const void * data, std::size_t len)
Referenced by ufsecp_tagged_hash().
taproot_branch_hash()
std::array< std::uint8_t, 32 > secp256k1::taproot_branch_hash (const std::array< std::uint8_t, 32 > & a, const std::array< std::uint8_t, 32 > & b)
taproot_leaf_hash()
std::array< std::uint8_t, 32 > secp256k1::taproot_leaf_hash (const std::uint8_t * script, std::size_t script_len, std::uint8_t leaf_version = 0xC0)
taproot_merkle_root()
std::array< std::uint8_t, 32 > secp256k1::taproot_merkle_root (const std::vector< std::array< std::uint8_t, 32 > > & leaf_hashes)
taproot_merkle_root_from_proof()
std::array< std::uint8_t, 32 > secp256k1::taproot_merkle_root_from_proof (const std::array< std::uint8_t, 32 > & leaf_hash, const std::vector< std::array< std::uint8_t, 32 > > & proof)
taproot_output_key()
std::pair< std::array< std::uint8_t, 32 >, int > secp256k1::taproot_output_key (const std::array< std::uint8_t, 32 > & internal_key_x, const std::uint8_t * merkle_root = nullptr, std::size_t merkle_root_len = 0)
Referenced by ufsecp_taproot_output_key().
taproot_tweak_hash()
std::array< std::uint8_t, 32 > secp256k1::taproot_tweak_hash (const std::array< std::uint8_t, 32 > & internal_key_x, const std::uint8_t * merkle_root = nullptr, std::size_t merkle_root_len = 0)
taproot_tweak_privkey()
Scalar secp256k1::taproot_tweak_privkey (const Scalar & private_key, const std::uint8_t * merkle_root = nullptr, std::size_t merkle_root_len = 0)
Referenced by ufsecp_taproot_tweak_seckey().
taproot_verify_commitment()
bool secp256k1::taproot_verify_commitment (const std::array< std::uint8_t, 32 > & output_key_x, int output_key_parity, const std::array< std::uint8_t, 32 > & internal_key_x, const std::uint8_t * merkle_root = nullptr, std::size_t merkle_root_len = 0)
Referenced by ufsecp_taproot_verify().
wif_decode()
WIFDecodeResult secp256k1::wif_decode (const std::string & wif)
Referenced by ufsecp_wif_decode().
wif_encode()
std::string secp256k1::wif_encode (const fast::Scalar & private_key, bool compressed = true, Network net = Network::Mainnet)
Referenced by ufsecp_wif_encode().