UltrafastSecp256k1: secp256k1::ExtendedKey Struct Reference
secp256k1::ExtendedKey Struct Reference
#include <bip32.hpp>
Public Member Functions
std::pair< ExtendedKey, bool > derive_child (std::uint32_t index) const
std::pair< ExtendedKey, bool > derive_normal (std::uint32_t index) const
std::pair< ExtendedKey, bool > derive_hardened (std::uint32_t index) const
fast::Point public_key () const
fast::Scalar private_key () const
ExtendedKey to_public () const
std::array< std::uint8_t, 78 > serialize () const
std::array< std::uint8_t, 4 > fingerprint () const
Public Attributes
std::array< std::uint8_t, 32 > key
std::array< std::uint8_t, 32 > chain_code
std::uint8_t depth
std::uint32_t child_number
std::array< std::uint8_t, 4 > parent_fingerprint
bool is_private
Detailed Description
Definition at line 29 of file bip32.hpp.
Member Function Documentation
derive_child()
std::pair< ExtendedKey, bool > secp256k1::ExtendedKey::derive_child (std::uint32_t index) const
Referenced by derive_hardened(), and derive_normal().
derive_hardened()
std::pair< ExtendedKey, bool > secp256k1::ExtendedKey::derive_hardened (std::uint32_t index) const inline
Definition at line 48 of file bip32.hpp.
References derive_child().
derive_normal()
std::pair< ExtendedKey, bool > secp256k1::ExtendedKey::derive_normal (std::uint32_t index) const inline
Definition at line 45 of file bip32.hpp.
References derive_child().
fingerprint()
std::array< std::uint8_t, 4 > secp256k1::ExtendedKey::fingerprint () const
private_key()
fast::Scalar secp256k1::ExtendedKey::private_key () const
public_key()
fast::Point secp256k1::ExtendedKey::public_key () const
serialize()
std::array< std::uint8_t, 78 > secp256k1::ExtendedKey::serialize () const
to_public()
ExtendedKey secp256k1::ExtendedKey::to_public () const
Member Data Documentation
chain_code
std::array<std::uint8_t, 32> secp256k1::ExtendedKey::chain_code
Definition at line 31 of file bip32.hpp.
child_number
std::uint32_t secp256k1::ExtendedKey::child_number
Definition at line 33 of file bip32.hpp.
depth
std::uint8_t secp256k1::ExtendedKey::depth
Definition at line 32 of file bip32.hpp.
is_private
bool secp256k1::ExtendedKey::is_private
Definition at line 35 of file bip32.hpp.
key
std::array<std::uint8_t, 32> secp256k1::ExtendedKey::key
Definition at line 30 of file bip32.hpp.
parent_fingerprint
std::array<std::uint8_t, 4> secp256k1::ExtendedKey::parent_fingerprint
Definition at line 34 of file bip32.hpp.
The documentation for this struct was generated from the following file:
cpu/include/secp256k1/bip32.hpp